# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(749, 858)
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 204, 153);\n"
"border: 2px solid #094065")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 10, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.remove_user_button = QtWidgets.QPushButton(Form)
        self.remove_user_button.setGeometry(QtCore.QRect(60, 720, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.remove_user_button.setFont(font)
        self.remove_user_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(224, 32, 32);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.remove_user_button.setObjectName("remove_user_button")
        self.enter_name_lineedit = QtWidgets.QLineEdit(Form)
        self.enter_name_lineedit.setGeometry(QtCore.QRect(60, 610, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_name_lineedit.setFont(font)
        self.enter_name_lineedit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.enter_name_lineedit.setText("")
        self.enter_name_lineedit.setObjectName("enter_name_lineedit")
        self.add_user_button = QtWidgets.QPushButton(Form)
        self.add_user_button.setGeometry(QtCore.QRect(370, 610, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.add_user_button.setFont(font)
        self.add_user_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(128, 128, 192);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.add_user_button.setObjectName("add_user_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 90, 371, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_label = QtWidgets.QLabel(Form)
        self.error_label.setGeometry(QtCore.QRect(30, 770, 701, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 670, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(530, 680, 20, 21))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.enter_button = QtWidgets.QPushButton(Form)
        self.enter_button.setGeometry(QtCore.QRect(560, 670, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.enter_button.setFont(font)
        self.enter_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(120, 183, 140);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.enter_button.setObjectName("enter_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Выбрать пользователя"))
        self.remove_user_button.setText(_translate("Form", "Удалить пользователя"))
        self.add_user_button.setText(_translate("Form", "Добавить пользователя"))
        self.label_2.setText(_translate("Form", "При открытии всегда выбирать пользователя"))
        self.enter_button.setText(_translate("Form", "Войти"))
