# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'months_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1843, 895)
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 204, 153);\n"
"border: 2px solid #094065")
        self.go_back_button = QtWidgets.QPushButton(Form)
        self.go_back_button.setGeometry(QtCore.QRect(10, 20, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.go_back_button.setFont(font)
        self.go_back_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.go_back_button.setObjectName("go_back_button")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(270, 90, 401, 671))
        self.scrollArea.setMinimumSize(QtCore.QSize(401, 581))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 667))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.test_label.setMinimumSize(QtCore.QSize(0, 71))
        self.test_label.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_label.setFont(font)
        self.test_label.setText("")
        self.test_label.setObjectName("test_label")
        self.verticalLayout.addWidget(self.test_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.comboBox_choose_month = QtWidgets.QComboBox(Form)
        self.comboBox_choose_month.setGeometry(QtCore.QRect(30, 150, 231, 31))
        self.comboBox_choose_month.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.comboBox_choose_month.setObjectName("comboBox_choose_month")
        self.label_stat_per_month = QtWidgets.QLabel(Form)
        self.label_stat_per_month.setGeometry(QtCore.QRect(300, 20, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_stat_per_month.setFont(font)
        self.label_stat_per_month.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_stat_per_month.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stat_per_month.setObjectName("label_stat_per_month")
        self.test_label_2 = QtWidgets.QLabel(Form)
        self.test_label_2.setGeometry(QtCore.QRect(920, 10, 211, 71))
        self.test_label_2.setMinimumSize(QtCore.QSize(0, 71))
        self.test_label_2.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_label_2.setFont(font)
        self.test_label_2.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.test_label_2.setText("")
        self.test_label_2.setObjectName("test_label_2")
        self.graph_categories = PlotWidget(Form)
        self.graph_categories.setGeometry(QtCore.QRect(690, 90, 851, 301))
        self.graph_categories.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.graph_categories.setObjectName("graph_categories")
        self.label_stat_for_categories = QtWidgets.QLabel(Form)
        self.label_stat_for_categories.setGeometry(QtCore.QRect(690, 30, 851, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_stat_for_categories.setFont(font)
        self.label_stat_for_categories.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_stat_for_categories.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stat_for_categories.setObjectName("label_stat_for_categories")
        self.comboBox_choose_category = QtWidgets.QComboBox(Form)
        self.comboBox_choose_category.setGeometry(QtCore.QRect(1570, 130, 201, 31))
        self.comboBox_choose_category.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.comboBox_choose_category.setObjectName("comboBox_choose_category")
        self.graph_incomes = PlotWidget(Form)
        self.graph_incomes.setGeometry(QtCore.QRect(690, 460, 851, 301))
        self.graph_incomes.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.graph_incomes.setObjectName("graph_incomes")
        self.label_stat_f_months_2 = QtWidgets.QLabel(Form)
        self.label_stat_f_months_2.setGeometry(QtCore.QRect(690, 400, 851, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_stat_f_months_2.setFont(font)
        self.label_stat_f_months_2.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_stat_f_months_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stat_f_months_2.setObjectName("label_stat_f_months_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1570, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_choose_year = QtWidgets.QComboBox(Form)
        self.comboBox_choose_year.setGeometry(QtCore.QRect(1570, 230, 201, 31))
        self.comboBox_choose_year.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.comboBox_choose_year.setObjectName("comboBox_choose_year")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1570, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.go_back_button.setText(_translate("Form", "Вернуться к статистике по дням"))
        self.label_stat_per_month.setText(_translate("Form", "Статистика за"))
        self.label_stat_for_categories.setText(_translate("Form", "Статистика по выбранной категории"))
        self.label_stat_f_months_2.setText(_translate("Form", "Статистика по доходам"))
        self.label.setText(_translate("Form", "Выбрать категорию"))
        self.label_2.setText(_translate("Form", "Выбрать Месяц"))
        self.label_3.setText(_translate("Form", "Выбрать год"))
from pyqtgraph import PlotWidget
