# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1948, 1014)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 204, 153);\n"
"border: 2px solid #094065")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 200, 641, 251))
        self.widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid #094065")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 150, 591, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollarea_day_statistics = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollarea_day_statistics.setGeometry(QtCore.QRect(1050, 150, 401, 301))
        self.scrollarea_day_statistics.setWidgetResizable(False)
        self.scrollarea_day_statistics.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollarea_day_statistics.setObjectName("scrollarea_day_statistics")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.test_label.setMinimumSize(QtCore.QSize(0, 70))
        self.test_label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.test_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.test_label.setText("")
        self.test_label.setObjectName("test_label")
        self.verticalLayout.addWidget(self.test_label)
        self.scrollarea_day_statistics.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.day_statistics_label = QtWidgets.QLabel(self.centralwidget)
        self.day_statistics_label.setGeometry(QtCore.QRect(1050, 100, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.day_statistics_label.setFont(font)
        self.day_statistics_label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.day_statistics_label.setAlignment(QtCore.Qt.AlignCenter)
        self.day_statistics_label.setObjectName("day_statistics_label")
        self.widget_2 = PlotWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(60, 590, 641, 251))
        self.widget_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid #094065")
        self.widget_2.setObjectName("widget_2")
        self.category_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.category_comboBox.setGeometry(QtCore.QRect(720, 690, 161, 22))
        self.category_comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.category_comboBox.setObjectName("category_comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 530, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.show_last_month_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_last_month_button.setGeometry(QtCore.QRect(50, 40, 261, 41))
        self.show_last_month_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.show_last_month_button.setObjectName("show_last_month_button")
        self.scrollArea_category_labels = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_category_labels.setGeometry(QtCore.QRect(850, 170, 120, 341))
        self.scrollArea_category_labels.setMinimumSize(QtCore.QSize(120, 341))
        self.scrollArea_category_labels.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_category_labels.setStyleSheet("")
        self.scrollArea_category_labels.setWidgetResizable(False)
        self.scrollArea_category_labels.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_category_labels.setObjectName("scrollArea_category_labels")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 118, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 41))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 41))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.scrollArea_category_labels.setWidget(self.scrollAreaWidgetContents_2)
        self.incomes_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.incomes_edit.setGeometry(QtCore.QRect(1360, 600, 231, 20))
        self.incomes_edit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.incomes_edit.setObjectName("incomes_edit")
        self.button_add_summ_to_income = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_summ_to_income.setGeometry(QtCore.QRect(1360, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_add_summ_to_income.setFont(font)
        self.button_add_summ_to_income.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(120, 183, 140);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.button_add_summ_to_income.setObjectName("button_add_summ_to_income")
        self.button_edit_income = QtWidgets.QPushButton(self.centralwidget)
        self.button_edit_income.setGeometry(QtCore.QRect(1480, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_edit_income.setFont(font)
        self.button_edit_income.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(128, 128, 192);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.button_edit_income.setObjectName("button_edit_income")
        self.income_per_day = QtWidgets.QLabel(self.centralwidget)
        self.income_per_day.setGeometry(QtCore.QRect(1360, 560, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.income_per_day.setFont(font)
        self.income_per_day.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.income_per_day.setObjectName("income_per_day")
        self.income_per_month = QtWidgets.QLabel(self.centralwidget)
        self.income_per_month.setGeometry(QtCore.QRect(630, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.income_per_month.setFont(font)
        self.income_per_month.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.income_per_month.setObjectName("income_per_month")
        self.expenses_per_month = QtWidgets.QLabel(self.centralwidget)
        self.expenses_per_month.setGeometry(QtCore.QRect(380, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expenses_per_month.setFont(font)
        self.expenses_per_month.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.expenses_per_month.setObjectName("expenses_per_month")
        self.total = QtWidgets.QLabel(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(910, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total.setFont(font)
        self.total.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.total.setObjectName("total")
        self.edit_expenses_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_expenses_button.setGeometry(QtCore.QRect(1100, 570, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_expenses_button.setFont(font)
        self.edit_expenses_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(128, 128, 192);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.edit_expenses_button.setObjectName("edit_expenses_button")
        self.income_error_label = QtWidgets.QLabel(self.centralwidget)
        self.income_error_label.setGeometry(QtCore.QRect(1610, 600, 161, 21))
        self.income_error_label.setText("")
        self.income_error_label.setObjectName("income_error_label")
        self.graph_about_income = PlotWidget(self.centralwidget)
        self.graph_about_income.setGeometry(QtCore.QRect(1480, 150, 391, 301))
        self.graph_about_income.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #094065")
        self.graph_about_income.setObjectName("graph_about_income")
        self.income_statistics_label = QtWidgets.QLabel(self.centralwidget)
        self.income_statistics_label.setGeometry(QtCore.QRect(1480, 90, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.income_statistics_label.setFont(font)
        self.income_statistics_label.setStyleSheet("border-color: rgb(255, 204, 153);\n"
"color: rgb(0, 0, 0);")
        self.income_statistics_label.setAlignment(QtCore.Qt.AlignCenter)
        self.income_statistics_label.setObjectName("income_statistics_label")
        self.show_statistics_for_months_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_statistics_for_months_button.setGeometry(QtCore.QRect(1520, 30, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_statistics_for_months_button.setFont(font)
        self.show_statistics_for_months_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.show_statistics_for_months_button.setObjectName("show_statistics_for_months_button")
        self.change_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_user_button.setGeometry(QtCore.QRect(30, 870, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.change_user_button.setFont(font)
        self.change_user_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 15px;\n"
"border: 2px solid #094065")
        self.change_user_button.setObjectName("change_user_button")
        self.pix_label = QtWidgets.QLabel(self.centralwidget)
        self.pix_label.setGeometry(QtCore.QRect(720, 160, 101, 487))
        self.pix_label.setStyleSheet("")
        self.pix_label.setText("")
        self.pix_label.setObjectName("pix_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>background-color: green;</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Статистика за каждый день месяца"))
        self.day_statistics_label.setText(_translate("MainWindow", "Подробная статистика за день"))
        self.label.setText(_translate("MainWindow", "Статистика по выбранной категории"))
        self.show_last_month_button.setText(_translate("MainWindow", "Показать статистику за прошлый месяц"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.button_add_summ_to_income.setText(_translate("MainWindow", "Добавить"))
        self.button_edit_income.setText(_translate("MainWindow", "Изменить"))
        self.income_per_day.setText(_translate("MainWindow", "Доход за день:"))
        self.income_per_month.setText(_translate("MainWindow", "Доходы за месяц:"))
        self.expenses_per_month.setText(_translate("MainWindow", "Расходы за месяц:"))
        self.total.setText(_translate("MainWindow", "Итог:"))
        self.edit_expenses_button.setText(_translate("MainWindow", "Изменить Расходы "))
        self.income_statistics_label.setText(_translate("MainWindow", "Cтатистика по доходам"))
        self.show_statistics_for_months_button.setText(_translate("MainWindow", "Показать статистику за прошлые месяцы"))
        self.change_user_button.setText(_translate("MainWindow", "Сменить пользователя"))
        self.action.setText(_translate("MainWindow", "Авторы"))
from pyqtgraph import PlotWidget
